spring.application.name=quarry-batch

spring.datasource.url=jdbc:postgresql://localhost:5432/quarry_db
spring.datasource.username=postgres
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always